# Generated by Django 6.0.4 on 2026-04-23 06:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='XOF', max_length=5)),
                ('operator', models.CharField(choices=[('orange_money', 'Orange Money'), ('moov_money', 'Moov Money'), ('cash', 'Espèces')], max_length=15)),
                ('phone_number', models.CharField(max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=10)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Paiement',
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='PricingSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_per_minute', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('delivery_base_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('delivery_price_per_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=15, max_digits=4)),
                ('minimum_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('maximum_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre tarifaire',
                'db_table': 'pricing_settings',
            },
        ),
        migrations.CreateModel(
            name='DriverEarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('earning_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='drivers.driverprofile')),
            ],
            options={
                'verbose_name': 'Gain conducteur',
                'db_table': 'driver_earnings',
            },
        ),
    ]
