# Generated by Django 6.0.4 on 2026-04-23 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverearning',
            name='ride',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_earning_payment', to='rides.ride'),
        ),
    ]
