# Generated by Django 6.0.4 on 2026-04-23 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_initial'),
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='ride',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='rides.ride'),
        ),
        migrations.AddField(
            model_name='pricingsetting',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='driverearning',
            index=models.Index(fields=['driver', 'earning_date'], name='driver_earn_driver__c7f84b_idx'),
        ),
        migrations.AddIndex(
            model_name='driverearning',
            index=models.Index(fields=['driver', 'is_paid'], name='driver_earn_driver__efcf4f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['client', 'status'], name='payments_client__d2fdbb_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_reference'], name='payments_transac_4c44f7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'initiated_at'], name='payments_status_7c686a_idx'),
        ),
    ]
