# Generated by Django 6.0.4 on 2026-05-17 17:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_initial'),
        ('payments', '0003_initial'),
        ('rides', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LigdiCashPayin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='XOF', max_length=5)),
                ('invoice_token', models.CharField(blank=True, max_length=500, null=True)),
                ('ligdicash_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('otp_sent', 'OTP envoyé'), ('pending', 'En attente de validation'), ('completed', 'Complété'), ('failed', 'Échoué'), ('expired', 'Expiré')], default='otp_sent', max_length=15)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('callback_received', models.BooleanField(default=False)),
                ('callback_data', models.JSONField(blank=True, null=True)),
                ('wallet_credited', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LigdiCash Payin',
                'db_table': 'ligdicash_payins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigdiCashPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_to_receive', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('withdrawal_token', models.CharField(blank=True, max_length=500, null=True)),
                ('ligdicash_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué')], default='pending', max_length=15)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('callback_received', models.BooleanField(default=False)),
                ('callback_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LigdiCash Payout',
                'db_table': 'ligdicash_payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiraWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('active', 'Actif'), ('frozen', 'Gelé'), ('closed', 'Fermé')], default='active', max_length=10)),
                ('freeze_reason', models.TextField(blank=True, null=True)),
                ('total_credited', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_debited', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wallet SIRA',
                'db_table': 'sira_wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('depot', 'Dépôt Mobile Money'), ('retrait', 'Retrait Mobile Money'), ('paiement_course', 'Paiement course'), ('reception_course', 'Réception course'), ('commission', 'Commission SIRA'), ('remboursement', 'Remboursement'), ('frais_annulation', 'Frais annulation'), ('commission_retrait', 'Commission retrait')], max_length=20)),
                ('direction', models.CharField(choices=[('credit', 'Crédit'), ('debit', 'Débit')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='XOF', max_length=5)),
                ('status', models.CharField(choices=[('success', 'Réussi'), ('failed', 'Échoué'), ('reversed', 'Annulé')], default='success', max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transaction Wallet',
                'db_table': 'wallet_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_client__d2fdbb_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_transac_4c44f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_status_7c686a_idx',
        ),
        migrations.RemoveField(
            model_name='driverearning',
            name='payment_reference',
        ),
        migrations.AlterField(
            model_name='driverearning',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driverprofile'),
        ),
        migrations.AlterField(
            model_name='driverearning',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='rides.ride'),
        ),
        migrations.AlterField(
            model_name='pricingsetting',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=4),
        ),
        migrations.AddField(
            model_name='ligdicashpayin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligdicash_payins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ligdicashpayout',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligdicash_payouts', to='drivers.driverprofile'),
        ),
        migrations.AddField(
            model_name='sirawallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ligdicashpayout',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligdicash_payouts', to='payments.sirawallet'),
        ),
        migrations.AddField(
            model_name='ligdicashpayin',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligdicash_payins', to='payments.sirawallet'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='related_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.wallettransaction'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='rides.ride'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.sirawallet'),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='ride',
        ),
        migrations.AddIndex(
            model_name='ligdicashpayout',
            index=models.Index(fields=['driver', 'status'], name='ligdicash_p_driver__d64c2e_idx'),
        ),
        migrations.AddIndex(
            model_name='ligdicashpayout',
            index=models.Index(fields=['withdrawal_token'], name='ligdicash_p_withdra_5a056d_idx'),
        ),
        migrations.AddIndex(
            model_name='ligdicashpayin',
            index=models.Index(fields=['user', 'status'], name='ligdicash_p_user_id_abc8a5_idx'),
        ),
        migrations.AddIndex(
            model_name='ligdicashpayin',
            index=models.Index(fields=['invoice_token'], name='ligdicash_p_invoice_6129f1_idx'),
        ),
        migrations.AddIndex(
            model_name='ligdicashpayin',
            index=models.Index(fields=['status', 'created_at'], name='ligdicash_p_status_1cd130_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'created_at'], name='wallet_tran_wallet__aa27da_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['transaction_type', 'status'], name='wallet_tran_transac_dcb2c5_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['ride'], name='wallet_tran_ride_id_449614_idx'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
