# Generated by Django 6.0.4 on 2026-04-23 06:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('photo_front', models.ImageField(blank=True, null=True, upload_to='vehicles/photos/')),
                ('photo_side', models.ImageField(blank=True, null=True, upload_to='vehicles/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='drivers.driverprofile')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'db_table': 'vehicles',
                'indexes': [models.Index(fields=['plate_number'], name='vehicles_plate_n_de64b1_idx')],
            },
        ),
    ]
