# Generated by Django 6.0.4 on 2026-05-30 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_adminuser_company_deliverypricinggrid_packagenature_and_more'),
        ('drivers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='admin_panel.company'),
        ),
    ]
