# Generated by Django 6.0.4 on 2026-04-23 06:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('accepted', 'Acceptée'), ('driver_en_route', 'Conducteur en route'), ('started', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='accepted', max_length=20)),
                ('actual_pickup_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('actual_pickup_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('actual_dropoff_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('actual_dropoff_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('actual_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('actual_duration_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('base_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('distance_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('driver_earning', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('platform_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('orange_money', 'Orange Money'), ('moov_money', 'Moov Money'), ('cash', 'Espèces')], max_length=15, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('driver_arrived_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('was_offline', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'db_table': 'rides',
            },
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('passenger', 'Course passager'), ('delivery', 'Livraison')], default='passenger', max_length=10)),
                ('pickup_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_address', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_address', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_duration_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('cancelled', 'Annulée'), ('expired', 'Expirée')], default='pending', max_length=10)),
                ('cancelled_by', models.CharField(blank=True, choices=[('client', 'Client'), ('driver', 'Conducteur'), ('system', 'Système')], max_length=10, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('package_description', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demande de course',
                'db_table': 'ride_requests',
            },
        ),
    ]
