# Generated by Django 6.0.4 on 2026-04-23 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0002_initial'),
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_driver', to='drivers.driverprofile'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_requests', to='drivers.driverprofile'),
        ),
        migrations.AddField(
            model_name='ride',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ride', to='rides.riderequest'),
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['client', 'status'], name='ride_reques_client__8751e5_idx'),
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['status', 'created_at'], name='ride_reques_status_e57dca_idx'),
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['pickup_latitude', 'pickup_longitude'], name='ride_reques_pickup__ea8a74_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['client', 'status'], name='rides_client__2e8958_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['driver', 'status'], name='rides_driver__d736b9_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status', 'created_at'], name='rides_status_3bc8a0_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['is_paid'], name='rides_is_paid_164805_idx'),
        ),
    ]
