# Generated by Django 6.0.4 on 2026-04-23 06:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bearing', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('recorded_at', models.DateTimeField()),
                ('is_offline', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_points', to='drivers.driverprofile')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_points', to='rides.ride')),
            ],
            options={
                'verbose_name': 'Point GPS',
                'db_table': 'gps_points',
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['ride', 'sequence'], name='gps_points_ride_id_4c7c4e_idx'), models.Index(fields=['driver', 'recorded_at'], name='gps_points_driver__84020b_idx'), models.Index(fields=['is_offline', 'synced_at'], name='gps_points_is_offl_36c0c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='OfflineSyncQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_type', models.CharField(choices=[('gps_points', 'Points GPS'), ('ride_status', 'Statut course'), ('payment', 'Paiement')], max_length=15)),
                ('payload', models.JSONField()),
                ('sync_status', models.CharField(choices=[('pending', 'En attente'), ('synced', 'Synchronisé'), ('failed', 'Échoué')], default='pending', max_length=10)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_queue', to='drivers.driverprofile')),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_queue', to='rides.ride')),
            ],
            options={
                'verbose_name': 'File de synchronisation offline',
                'db_table': 'offline_sync_queue',
                'ordering': ['recorded_at'],
                'indexes': [models.Index(fields=['driver', 'sync_status'], name='offline_syn_driver__1e2d7a_idx'), models.Index(fields=['sync_status', 'created_at'], name='offline_syn_sync_st_c31e45_idx')],
            },
        ),
    ]
