# Generated by Django 6.0.4 on 2026-04-23 06:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispute_type', models.CharField(choices=[('overcharge', 'Surfacturation'), ('wrong_route', 'Mauvais itinéraire'), ('driver_behavior', 'Comportement conducteur'), ('payment_issue', 'Problème de paiement'), ('lost_item', 'Objet perdu'), ('other', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='disputes/evidence/')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('in_review', "En cours d'examen"), ('resolved', 'Résolu'), ('closed', 'Fermé')], default='open', max_length=10)),
                ('resolution', models.CharField(blank=True, choices=[('favor_client', 'En faveur du client'), ('favor_driver', 'En faveur du conducteur'), ('compromise', 'Compromis'), ('no_action', 'Aucune action')], max_length=15, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Litige',
                'db_table': 'disputes',
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('user_login', 'Connexion utilisateur'), ('driver_validated', 'Conducteur validé'), ('driver_rejected', 'Conducteur rejeté'), ('user_suspended', 'Utilisateur suspendu'), ('user_banned', 'Utilisateur banni'), ('fraud_detected', 'Fraude détectée'), ('pricing_updated', 'Tarif mis à jour'), ('payment_processed', 'Paiement traité'), ('dispute_resolved', 'Litige résolu'), ('ride_force_ended', 'Course terminée de force')], max_length=25)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Journal système',
                'db_table': 'system_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
