# Generated by Django 6.0.4 on 2026-05-30 00:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('super_admin', 'Super Administrateur'), ('admin', 'Administrateur'), ('manager', 'Manager')], default='admin', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin User',
                'db_table': 'admin_users',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/')),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='DeliveryPricingGrid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Grille tarifaire SIRA', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('price_per_km_pickup', models.DecimalField(decimal_places=2, default=150, max_digits=8)),
                ('price_per_km_delivery', models.DecimalField(decimal_places=2, default=200, max_digits=8)),
                ('base_fare', models.DecimalField(decimal_places=2, default=500, max_digits=8)),
                ('min_fare', models.DecimalField(decimal_places=2, default=800, max_digits=8)),
                ('waiting_time_rate', models.DecimalField(decimal_places=2, default=50, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grille tarifaire livraison',
                'db_table': 'delivery_pricing_grids',
            },
        ),
        migrations.CreateModel(
            name='PackageNature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nature_id', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('icon', models.CharField(default='📦', max_length=10)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('compatible_vehicles', models.JSONField(default=list)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'package_natures',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ValueSlab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'value_slabs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_id', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('icon', models.CharField(default='🛵', max_length=10)),
                ('max_weight_kg', models.DecimalField(decimal_places=2, max_digits=7)),
                ('max_value_fcfa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('base_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'vehicle_types',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WeightSlab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('max_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'weight_slabs',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='dispute',
            options={'ordering': ['-created_at'], 'verbose_name': 'Litige'},
        ),
        migrations.AlterModelOptions(
            name='systemlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='dispute',
            name='disputes_status_536461_idx',
        ),
        migrations.RemoveIndex(
            model_name='dispute',
            name='disputes_filed_b_ddc4d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='systemlog',
            name='system_logs_action_bb3eda_idx',
        ),
        migrations.RemoveIndex(
            model_name='systemlog',
            name='system_logs_perform_51cae2_idx',
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='action',
            field=models.CharField(choices=[('user_login', 'Connexion utilisateur'), ('driver_validated', 'Conducteur validé'), ('driver_rejected', 'Conducteur rejeté'), ('user_suspended', 'Utilisateur suspendu'), ('user_banned', 'Utilisateur banni'), ('fraud_detected', 'Fraude détectée'), ('pricing_updated', 'Tarif mis à jour'), ('payment_processed', 'Paiement traité'), ('dispute_resolved', 'Litige résolu'), ('ride_force_ended', 'Course terminée de force'), ('admin_login', 'Connexion admin')], max_length=25),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to='admin_panel.adminuser'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_assigned', to='admin_panel.adminuser'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='admin_panel.company'),
        ),
        migrations.AddField(
            model_name='deliverypricinggrid',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_pricing', to='admin_panel.company'),
        ),
        migrations.AddField(
            model_name='packagenature',
            name='grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_natures', to='admin_panel.deliverypricinggrid'),
        ),
        migrations.AddField(
            model_name='valueslab',
            name='grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_slabs', to='admin_panel.deliverypricinggrid'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_types', to='admin_panel.deliverypricinggrid'),
        ),
        migrations.AddField(
            model_name='weightslab',
            name='grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_slabs', to='admin_panel.deliverypricinggrid'),
        ),
        migrations.RemoveField(
            model_name='systemlog',
            name='performed_by',
        ),
    ]
