# Generated by Django 6.0.4 on 2026-06-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_adminuser_company_deliverypricinggrid_packagenature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='icon',
            field=models.CharField(default='🛵', max_length=20),
        ),
    ]
