# Generated by Django 6.0.4 on 2026-06-05 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_vehicletype_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemlog',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='resolution',
        ),
        migrations.AddField(
            model_name='systemlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='action',
            field=models.CharField(choices=[('driver_validated', 'Conducteur validé'), ('driver_rejected', 'Conducteur rejeté'), ('user_suspended', 'Utilisateur suspendu'), ('user_banned', 'Utilisateur banni'), ('fraud_detected', 'Fraude détectée'), ('pricing_updated', 'Tarif mis à jour'), ('admin_login', 'Connexion admin')], max_length=25),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_about', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='icon',
            field=models.CharField(default='🛵', max_length=10),
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
