# Generated by Django 6.0.4 on 2026-04-23 06:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gps_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('theoretical_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('distance_deviation_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('average_speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('speed_violations', models.PositiveSmallIntegerField(default=0)),
                ('has_gps_gaps', models.BooleanField(default=False)),
                ('has_route_deviation', models.BooleanField(default=False)),
                ('has_speed_anomaly', models.BooleanField(default=False)),
                ('has_distance_mismatch', models.BooleanField(default=False)),
                ('risk_level', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='low', max_length=10)),
                ('check_status', models.CharField(choices=[('pending', 'En attente'), ('cleared', 'Sans fraude'), ('flagged', 'Signalé'), ('confirmed', 'Fraude confirmée')], default='pending', max_length=10)),
                ('fraud_score', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_checks', to='drivers.driverprofile')),
            ],
            options={
                'verbose_name': 'Contrôle anti-fraude',
                'db_table': 'fraud_checks',
            },
        ),
    ]
