# Generated by Django 6.0.4 on 2026-04-23 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fraud_detection', '0001_initial'),
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudcheck',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudcheck',
            name='ride',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_check', to='rides.ride'),
        ),
        migrations.AddIndex(
            model_name='fraudcheck',
            index=models.Index(fields=['check_status', 'risk_level'], name='fraud_check_check_s_59cd72_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudcheck',
            index=models.Index(fields=['driver', 'check_status'], name='fraud_check_driver__0d8d67_idx'),
        ),
    ]
