# Generated by Django 6.0.4 on 2026-05-15 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_initial'),
        ('fraud_detection', '0002_initial'),
        ('rides', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fraudcheck',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contrôle anti-fraude'},
        ),
        migrations.RemoveIndex(
            model_name='fraudcheck',
            name='fraud_check_check_s_59cd72_idx',
        ),
        migrations.RemoveIndex(
            model_name='fraudcheck',
            name='fraud_check_driver__0d8d67_idx',
        ),
        migrations.RenameField(
            model_name='fraudcheck',
            old_name='speed_violations',
            new_name='speed_violations_count',
        ),
        migrations.AddField(
            model_name='fraudcheck',
            name='detour_justified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fraudcheck',
            name='detour_km',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='fraudcheck',
            name='incidents',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='fraudcheck',
            name='speed_limit_zone',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AddField(
            model_name='fraudcheck',
            name='statut',
            field=models.CharField(choices=[('ok', 'OK'), ('avertissement', 'Avertissement'), ('alerte', 'Alerte')], default='ok', max_length=15),
        ),
        migrations.AlterField(
            model_name='fraudcheck',
            name='distance_deviation_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='fraudcheck',
            name='gps_distance_km',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='fraudcheck',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fraud_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fraudcheck',
            name='theoretical_distance_km',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddIndex(
            model_name='fraudcheck',
            index=models.Index(fields=['statut', 'check_status'], name='fraud_check_statut_da78f3_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudcheck',
            index=models.Index(fields=['driver', 'created_at'], name='fraud_check_driver__6e127a_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudcheck',
            index=models.Index(fields=['fraud_score'], name='fraud_check_fraud_s_5f4b9c_idx'),
        ),
    ]
