# Generated by Django 6.0.4 on 2026-04-23 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0002_initial'),
        ('reviews', '0001_initial'),
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='drivers.driverprofile'),
        ),
        migrations.AddField(
            model_name='review',
            name='ride',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='rides.ride'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['driver', 'rating'], name='reviews_driver__d6fd1c_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['client'], name='reviews_client__fcdabf_idx'),
        ),
    ]
