# Generated by Django 6.0.4 on 2026-04-23 06:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('ride_request', 'Nouvelle demande de course'), ('ride_accepted', 'Course acceptée'), ('ride_started', 'Course démarrée'), ('ride_completed', 'Course terminée'), ('ride_cancelled', 'Course annulée'), ('driver_arrived', 'Conducteur arrivé'), ('payment_success', 'Paiement réussi'), ('payment_failed', 'Paiement échoué'), ('account_approved', 'Compte approuvé'), ('account_suspended', 'Compte suspendu'), ('general', 'Général')], max_length=20)),
                ('channel', models.CharField(choices=[('push', 'Notification Push'), ('sms', 'SMS'), ('inapp', 'In-App')], default='inapp', max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('device_token', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
